[WIP] adding comparison chart to about page
FormidableLabs/formidable-charts-docs pull request #19
Opened 2016-10-31 23:33 UTC by ebrillhart

cc/ @paulathevalley @eliseworthy 

adding the comparison chart for when to use formidablecharts v. victory to the about page. going to flesh out with a paragraph or so. this seemed like the best place for it to live for now, until a more robust guide for upgrading to victory from formidablecharts can be created down the road.

2016-11-02 22:49 UTC, paulathevalley commented
Here’s what the comparison table looks like now, but I’d like copy review/approval from @boygirl @kenwheeler @eliseworthy 

![screen shot 2016-11-02 at 3 47 01 pm](https://cloud.githubusercontent.com/assets/768965/19950277/b652e42a-a113-11e6-92d8-a83d653e137c.png)

2016-11-03 18:27 UTC, boygirl requested changes
I really like the comparison table. 

Language like "muss and fuss" and "fiddling" all needs to go away, IMO.

2016-11-03 18:27 UTC, boygirl commented on src/screens/about/components/comparison.js
> +         However, Victory is much more flexible and powerful, and allows users to develop pretty much any kind of
The word "powerful" is not appropriate for Victory.

2016-11-03 18:27 UTC, boygirl commented on src/screens/about/components/comparison.js
> +                  <td>Advanced Chart Types</td>
They have the same chart types... So maybe "Pre-Built Charts" vs. "Modular Chart Components"

2016-11-03 18:27 UTC, boygirl commented on src/screens/about/components/comparison.js
> +                  <td>Advanced Chart Types</td>
"Automatic Interactive Events" vs. "Flexible Event System"
"Emphasis on Ease of Use" Vs. "Emphasis on Flexibility"

2016-11-03 18:27 UTC, boygirl commented on src/screens/about/components/comparison.js
> +                  <td>Custom Themes and Styles</td>
Data, theme, style stuff is true for both projects, I believe

2016-11-03 18:27 UTC, boygirl commented on src/screens/about/components/comparison.js
> +         chart configuration that they could need. Here's a chart to help you figure out what's best for your
chart -> table

2016-11-03 18:27 UTC, boygirl commented on src/screens/about/components/comparison.js
> +         quick and easy to implement with minimal muss and fuss around styling, theming, and composing components.
Dislike "muss and fuss".

2016-11-03 18:27 UTC, boygirl commented on src/screens/about/index.js
> +            FormidableCharts is a library that provides quick, composed charts out-of-the-box for React and other Javascript projects.
Dislike "fiddling"

2016-11-03 18:27 UTC, boygirl commented on src/screens/home/index.js
> +                      Build the charts you need quickly without the hassle of fitting the pieces together yourself.
Dislike "hassle"

2016-11-03 18:27 UTC, boygirl commented on src/screens/about/components/comparison.js
> +         quick and easy to implement with minimal muss and fuss around styling, theming, and composing components.
Focus on the positives of each. Maybe something more like "focus on the data with pre-built, easy to use charts" vs . "Use Victory to create fully custom charts that integrate seamlessly with the look and feel of your project."

2016-11-03 22:20 UTC, paulathevalley commented on src/screens/about/components/comparison.js
> +                  <td>Custom Themes and Styles</td>
There’s a lot of copy around "built-in themes" and "spend less time styling" etc. ...is this accurate? Or, does the copy need to be modified?

2016-11-03 22:31 UTC, paulathevalley commented
@boygirl Made some copy change requests! I still have some questions, but take a look. 

![screen shot 2016-11-03 at 3 28 30 pm](https://cloud.githubusercontent.com/assets/768965/19987815/3bd07be6-a1da-11e6-8aa6-4cf8daf93b1d.png)

Some questions: 
- There is some copy differentiating the ease of using prebuilt themes for FormidableCharts. Is there a way we could reflect that in the tables? 
- Both words "composed" and "prebuilt" are being used interchangeably. Is that helpful or confusing? Should we pick one? 
- Ideally, one table will be longer than the other to show that one project is more fully featured, robust, advanced, etc. First, is this true? Does Victory have features that FormidableCharts does not have?

2016-11-04 16:49 UTC, boygirl commented on src/screens/about/components/comparison.js
> +          Victory is much more flexible, allowing users to develop pretty much any kind of chart configuration. Create fully custom charts that integrate seamlessly with the look and feel of your pro
"Victory is much more flexible, allowing users to create fully custom charts that integrate seamlessly with the look and feel of a project."

I think "pretty much any kind of chart" is unnecessary.

2016-11-04 17:37 UTC, boygirl commented
@paulathevalley 

I think "Data Accessors" can be dropped from the table. Maybe ditto "series-style data" and "flexible data formats". Both have about equivalently flexible ways of handling data, just with slightly different organization. I'm not sure this detail is worth calling out.

I sticking with prebuilt, readymade etc is less confusing for formidable charts since we emphasize composability for victory


Maybe

| FormidableCharts  | Victory |
| ------------- | ------------- |
| Web and Native Charts | Web and Native Charts |
| Pre-built Charts | Modular Chart Components |
| Emphasizes ease of use | Emphasizes Flexibility |
| Automatic Animations | Configureable Animations |
| Automatic Interactive Events | Flexible Event System |
| Readymade themes | Custom themes and styles |

Victory has a few features that FormidableCharts doesn't have, like error bars and candlestick components, but for the most part you can create all the same chart types in FormidableCharts but with more limited options / a lot of stuff already configured for you. The main advanced feature of Victory is that it lets you write your own advanced features.

2016-11-04 18:05 UTC, paulathevalley commented
@boygirl Ok! Updated: 

<img width="632" alt="screen shot 2016-11-04 at 10 53 28 am" src="https://cloud.githubusercontent.com/assets/768965/20016499/f0585744-a27c-11e6-97f4-9ef66ccdc183.png">

Having only one similarity is not as visually obvious what it is, but it’s okay to leave it if needed. Could we split it the one similarity into two rows: Web Charts, Native Charts (or Native Support)?

I think it’s worth making the Victory table longer to keep the "it’s more advanced!" takeaway at a glance. So, ideas...
Custom Feature Support? 
Custom Advanced Features? 
Custom Component Support? 
Custom Chart Components (to match Modular Chart Components language)? 
DIY Components 😛 

Here’s what I’m thinking:
 
<img width="634" alt="screen shot 2016-11-04 at 10 58 27 am" src="https://cloud.githubusercontent.com/assets/768965/20016678/b0932836-a27d-11e6-8e53-81fabea8a235.png">
 
What do you think? (know that either option is totally ok!)

2016-11-04 20:10 UTC, boygirl commented
Option 2! "Custom Feature Support" is exactly what I was looking for.

2016-11-04 20:12 UTC, boygirl approved these changes

2016-11-04 20:13 UTC, boygirl commented
@paulathevalley Is this table going to end up somewhere on the victory lander too?

2016-11-04 21:01 UTC, paulathevalley commented
@boygirl Cool! Will do. 

After discussing with @eliseworthy, our thinking is that FormidableCharts is the entry point to Victory. I think of the typical workflow as a one-way street: FormidableCharts --> Victory. We’re thinking it is not likely for someone to start with Victory and go for something more limiting. I think of it like a video game: once you max out your achievements (aka push against the limits of FormidableCharts), you upgrade to the next level (Victory). Therefore, all the "transition" guides would be on FormidableCharts dox, including this table, since that's the starting point, and it does not make as much sense to duplicate them on Victory dox... as you’ve already upgraded by then.

However, the formidable-charts release and ad buy are changing things up a bit. We are planning to have a banner across the top of the Victory homepage that links to a blog post on formidable.com which describes/compares FormidableCharts and Victory (and I think other charting libraries too?). This blog post task is on @eliseworthy’s plate: I believe she might already be proofreading it? And it’s on my plate to create a visual mockup for it, but we haven’t finalized the wording of the banner yet. 

We can talk more about the banner/transition guides on Monday if that’s easier. I would definitely love to hear your thoughts on wording and this approach in general. 

For now, I’m going to merge!

2016-11-04 21:02 UTC, merged